site_url: https://wheelog-org.empty-shadow-6f25.workers.dev

backend:
  name: github
  repo: wheelog-app/org-astro
  branch: main
  auth_type: implicit

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "ニュース"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
